version: "3.7"

volumes:
  mysql_project:
    name: mysql_project

services:
  db:
    container_name: mysql_container
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: passwd
    volumes:
      - mysql_project:/var/lib/mysql
      - ./test_data:/backup