version: "3.7"

services:
  elasticsearch:
    container_name: container_elasticsearch
    image: centos:7
    restart: on-failure
    command: ["sleep", "infinity"]
  kibana:
    container_name: container_kibana
    image: centos:7
    restart: on-failure
    command: ["sleep", "infinity"]
